name: Check in

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build image"]
    types:
      - completed

  # UTC时间，对应Beijing时间 8：30
schedule:
- cron: "30 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    container:
      image: enwaiax/smzdm_bot
      env:
        ANDROID_COOKIE: ${{__ckguid=LxL36awKhpygeLKlsvCee5; device_id=187532987416939836294654374ed4b28aa74e299b69f53b4b05e4bc06; homepage_sug=b; r_sort_type=score; footer_floating_layer=0; ad_date=17; ad_json_feed=%7B%7D; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2218a694aee741a18-09885412e3693b-26031f51-3686400-18a694aee7511dc%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E8%87%AA%E7%84%B6%E6%90%9C%E7%B4%A2%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC%22%2C%22%24latest_referrer%22%3A%22https%3A%2F%2Fwww.bing.com%2F%22%2C%22%24latest_landing_page%22%3A%22https%3A%2F%2Fwww.smzdm.com%2F%22%7D%2C%22%24device_id%22%3A%2218a694aee741a18-09885412e3693b-26031f51-3686400-18a694aee7511dc%22%7D; _zdmA.vid=*; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1697530095; sess=BA-gj9pnI3YtbMjXHCcVAdgTeeXBZQJBQyclcUe7uRKc9F8oF%2Ff69XRKUqnFc%2B0h67edAye2WKvM20%2BKK2Or5gGFBeMue2wdUdUJg%2FbuAGYw6R6s3B5uyVjrQz%2F; user=user%3A1615626687%7C1615626687; smzdm_id=1615626687; _zdmA.uid=ZDMA.kj1mI_joX.1697530106.2419200; bannerCounter=%5B%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A1%2C%22surplus%22%3A1%7D%5D; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1697530107; _zdmA.time=1697530112119.0.https%3A%2F%2Fwww.smzdm.com%2F}}
        SK: ${{ secrets.SK }}
        PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        SC_KEY: ${{ secrets.SC_KEY }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_USER_ID: ${{ secrets.TG_USER_ID }}
        TG_BOT_API: ${{ secrets.TG_BOT_API }}
    steps:
      - name: Working
        run: |
          python /smzdm_bot/main.py
